#### SVR 

In [1]:
# Dealing with non-linear regression model

In [4]:
import os
os.getcwd()

'C:\\Users\\HP\\Udemy python\\supervised\\SVM'

In [5]:
os.chdir('C:\\Users\\HP\\Desktop\\Machine Learning A-Z\\Part 2 - Regression\\Section 7 - Support Vector Regression (SVR)')

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
data = pd.read_csv('Position_Salaries.csv')
data

Position  Level   Salary
0   Business Analyst      1    45000
1  Junior Consultant      2    50000
2  Senior Consultant      3    60000
3            Manager      4    80000
4    Country Manager      5   110000
5     Region Manager      6   150000
6            Partner      7   200000
7     Senior Partner      8   300000
8            C-level      9   500000
9                CEO     10  1000000

In [13]:
X = data.iloc[:,1:2].values
y = data.iloc[:,2].values
X,y

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]], dtype=int64),
 array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
         300000,  500000, 1000000], dtype=int64))

In [14]:
#Splitting the dataset into training and test tests

#from sklearn.model_selection import train_test_split
#X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 0)

In [17]:
# Feature scaling

# In most ML models we don't need to apply feature scaling because the libraries or other classes include feature scaling in 
# their algorithm 

# But SVR is a less commonly used class and this doesn't apply feature scaling in its algorithm
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

#when u are applying your standard scaler object to your training set u have to fit the object of the training set and then
#transform it, and when coming to test set we only transform and don't fit the object b'cause it's already fitted to the 
#training set.

## "fit" helps in fitting the StandardScaler() object to the matrix and "transform" helps in standardising the matrix

ValueError: Expected 2D array, got 1D array instead:
array=[  45000.   50000.   60000.   80000.  110000.  150000.  200000.  300000.
  500000. 1000000.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [18]:
X,y

(array([[-1.5666989 ],
        [-1.21854359],
        [-0.87038828],
        [-0.52223297],
        [-0.17407766],
        [ 0.17407766],
        [ 0.52223297],
        [ 0.87038828],
        [ 1.21854359],
        [ 1.5666989 ]]),
 array([  45000,   50000,   60000,   80000,  110000,  150000,  200000,
         300000,  500000, 1000000], dtype=int64))

In [19]:
# Fitting SVR to the dataset
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(X,y)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [23]:
# Predicting the result
#remember that this employee said that his previous salary was 160K and he's asking more during negotiation  
y_pred = regressor.predict()